.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "/Users/harshuljain/work/projects/experiments_and_courses/opensource/handy-ios/build-ios/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
